### PR TITLE
feat: latLongToPixels to display marker over map

### PR DESCRIPTION
**Pull request by EArminjon**
Feature : 

LatLong to Map position helper function.

This new function could maybe be used to create a marker feature with this package ? Using custom paint also for markers ?

Can fix : 

https://github.com/simplewidgets/countries_world_map/issues/16

Output example : I want to display a point on Lyon French City.

image

Usage example :
```dart
class Example extends StatelessWidget {
  const Example({super.key});

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (BuildContext context, BoxConstraints constraints) {
        final MapAttributes attributes = MapAttributes(
          SMapFrance.instructions,
        );

        /// Set size to restrict size of Stack Widget
        return ConstrainedBox(
          constraints: BoxConstraints(
            maxWidth: constraints.maxWidth,
            maxHeight: constraints.maxWidth / attributes.aspectRatio,
          ),
          child: LayoutBuilder(
            builder: (BuildContext context, BoxConstraints constraints) {
              /// Call latLongToPixels with LatLong of Lyon French city
              final Size position = attributes.latLongToPixels(
                const LatLong(latitude: 45.750000, longitude: 4.850000),
                constraints.biggest,
              );

              return Stack(
                children: <Widget>[
                  SimpleMap(
                    instructions: SMapFrance.instructions,
                    defaultColor: Theme.of(context).scaffoldBackgroundColor,
                    countryBorder: CountryBorder(
                      color: Theme.of(context).colorScheme.onPrimaryContainer,
                      width: 1,
                    ),
                  ),
                  Positioned(
                    left: position.width - (10 / 2),
                    top: position.height - (10 / 2),
                    child: const Icon(
                      Icons.circle,
                      size: 10,
                    ),
                  ),
                ],
              );
            },
          ),
        );
      },
    );
  }
}
```

### CODE REVIEW

**Comment by shivams1110** [comment]
@EArminjon Why u did this in **- (10 / 2)** in positioned Widget

**Comment by EArminjon** [comment]
> @EArminjon Why u did this **- (10 / 2)** in Positioned Widget?

Example purpose, it's to center my marker on the x/y position. (I did the marker example really fast)

**Comment by shivams1110** [comment]
Hi @EArminjon ,
I am using same code for placing marker in map but, in my case i m not getting proper position. Can you please help where i am wrong.
Screenshot 2023-11-02 at 2 34 12 PM

this is source code

`import 'package:countries_world_map/countries_world_map.dart';
import 'package:flutter/material.dart';
import 'package:k_common/utils/mapper_location_helper.dart';

class StoreAnalysis extends StatelessWidget {
  const StoreAnalysis({super.key});

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (BuildContext context, BoxConstraints constraints) {
        MapAttributes attributes = MapAttributes(SMapIndia.instructions);
        return ConstrainedBox(
          constraints: BoxConstraints(
            maxWidth: constraints.maxWidth,
            maxHeight: constraints.maxWidth / attributes.aspectRatio,
          ),
          child: LayoutBuilder(
            builder: (BuildContext context, BoxConstraints constraints) {
              final Size position = attributes.latLongToPixels(
                const LatLong(latitude: 28.644800, longitude: 77.216721), //Delhi
                constraints.biggest,
              );
              return Stack(
                children: [
                  const SimpleMap(
                    instructions: SMapIndia.instructions,
                    defaultColor: Colors.white,
                    countryBorder:
                        CountryBorder(color: Colors.black54, width: 0.4),
                  ),
                  Positioned(
                    left: position.width - (10 / 2),
                    top: position.height - (10 / 2),
                    child: const Icon(
                      Icons.circle,
                      size: 10,
                    ),
                  ),
                ],
              );
            },
          ),
        );
      },
    );
  }
}
`

**Comment by EArminjon** [comment]
Ty for your example i will check that.

**Comment by shivams1110** [comment]
I am also trying to figuring out what is the issue, so that i can help you

**Comment by LauDijksterhuis** [comment]
Hi @EArminjon 

Thank you for your pull request! I haven't had time to try this myself yet.
I will try to look at this weekend. If the marker works correctly on the maps I will merge it to the main branche

**Comment by shivams1110** [comment]
Hi @EArminjon 
need to wrap **ConstrainedBox** widget with **UnconstrainedBox** Widget like below:-

``` dart
class MapPointer extends StatelessWidget {
  const MapPointer({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Padding(
          padding: const EdgeInsets.all(16.0),
          child: LayoutBuilder(
            builder: (BuildContext context, BoxConstraints constraints) {
              final MapAttributes attributes = MapAttributes(
                SMapIndia.instructions,
              );
              /// Set size to restrict size of Stack Widget
              return UnconstrainedBox(
                child: ConstrainedBox(
                  constraints: BoxConstraints(
                    maxWidth: constraints.maxWidth,
                    maxHeight: constraints.maxWidth / attributes.aspectRatio,
                  ),
                  child: LayoutBuilder(
                    builder: (BuildContext context, BoxConstraints constraints) {
                      /// Call latLongToPixels with LatLong of Delhi India city
                      final Size position = attributes.latLongToPixels(
                         position: const LatLong(latitude: 28.61, longitude: 77.23),
                        widgetSize: constraints.biggest,
                        topLeft: attributes.topLeft,
                        bottomRight: attributes.bottomRight
                      );

                      return Stack(
                        children: <Widget>[
                          SimpleMap(
                            instructions: SMapIndia.instructions,
                            defaultColor: Theme.of(context).scaffoldBackgroundColor,
                            countryBorder: CountryBorder(
                              color: Theme.of(context).colorScheme.onPrimaryContainer,
                              width: 0.8,
                            ),
                          ),
                          Positioned(
                            left: position.width - (10 / 2),
                            top: position.height - (-10 / 2),
                            child: const Icon(
                              Icons.circle,
                              size: 8,
                            ),
                          ),
                        ],
                      );
                    },
                  ),
                ),
              );
            },
          ),
        ),
      ],
    );
  }
}

```

output as expected:-
home

**Comment by EArminjon** [comment]
That's weird, how does it work ? I need to investigate that this week

**Comment by EArminjon** [comment]
> ```dart
>   final Size position = attributes.latLongToPixels(
>                          position: const LatLong(latitude: 28.61, longitude: 77.23),
>                         widgetSize: constraints.biggest,
>                         topLeft: attributes.topLeft,
>                         bottomRight: attributes.bottomRight
>                       );
> ```

on your example you used :
```
  final Size position = attributes.latLongToPixels(
   position: const LatLong(latitude: 28.61, longitude: 77.23),
   widgetSize: constraints.biggest,
   topLeft: attributes.topLeft,
   bottomRight: attributes.bottomRight
 );
```

In my PR, latLongToPixels didn't take topLeft and bottomRight. So with your example, adding UnConstrainedBox did nothing for me.

**Comment by EArminjon** [comment]
```dart
import 'package:countries_world_map/countries_world_map.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: const Column(
        children: [
          Example(
            instruction: SMapIndia.instructions,
            markers: <LatLong>[
              LatLong(latitude: 28.61, longitude: 77.23),
            ],
            markerSize: 10,
          ),
        ],
      ),
    );
  }
}

class Example extends StatefulWidget {
  final String instruction;
  final List<LatLong>? markers;
  final double markerSize;

  const Example({
    super.key,
    required this.instruction,
    this.markers,
    this.markerSize = 10,
  });

  @override
  State<Example> createState() => _ExampleState();
}

class _ExampleState extends State<Example> {
  late MapAttributes attributes;

  @override
  void initState() {
    super.initState();
    attributes = MapAttributes(widget.instruction);
  }

  @override
  void didUpdateWidget(covariant Example oldWidget) {
    if (oldWidget.instruction != widget.instruction) {
      attributes = MapAttributes(widget.instruction);
    }
    super.didUpdateWidget(oldWidget);
  }

  @override
  Widget build(BuildContext context) {
    return FittedBox(
      alignment: Alignment.topLeft,
      fit: BoxFit.scaleDown,
      child: Stack(
        children: <Widget>[
          SimpleMap(
            instructions: widget.instruction,
            defaultColor: Theme.of(context).scaffoldBackgroundColor,
            countryBorder: CountryBorder(
              color: Theme.of(context).colorScheme.onPrimaryContainer,
              width: 1,
            ),
          ),
          ...?widget.markers?.map((marker) {
            final Size position = attributes.latLongToPixels(
              LatLong(
                latitude: marker.latitude,
                longitude: marker.longitude,
              ),
            );
            return Positioned(
              left: position.width - (widget.markerSize / 2),
              top: position.height - (widget.markerSize / 2),
              child: Icon(
                Icons.circle,
                size: widget.markerSize,
              ),
            );
          }).toList(),
        ],
      ),
    );
  }
}


Updated example, more simple and flexible I think.

The issue remain around longitude which is not enough precise.
```

**Comment by EArminjon** [comment]
If someone find a way to compute better the longitude it could be fantastic ! But I think it's maybe a limitation of 2D flat map projection :/ !

**Comment by LauDijksterhuis** [comment]
Hi @EArminjon ,

I checked out your helper function and I think it is really awesome!
As I tested it the Y axis seems to be off for a tiny amount, which I think is fine for now.

I have merged the commit and I will bring changes to the `SimpleMap` widget which reflects the last example code you added to the conversation (https://github.com/simplewidgets/countries_world_map/pull/20#issuecomment-1793401843) this way its possible to add Location Markers on the place it needs to be without manually wrapping it in a Stack widget.

Thank you for improving this package!

**Comment by EArminjon** [comment]
Nice !

I wonder about precision which is not perfect and that can be and is an issue. 

Didn't know how we can do.

**Comment by shivams1110** [comment]
@EArminjon That we can do with little bit move position hight and width for Positioned widget. Like i did in my case.

**Comment by EArminjon** [comment]
> @EArminjon That we can do with little bit move position hight and width for Positioned widget. Like i did in my case.

It didn't work well when positioning some list of latitude and longitude with precision. Sometimes the marker will be a little too high and sometimes a little too down.

**Comment by shivams1110** [comment]
> e too down.

We will try to fix this properly. But right now it is good we have something to put marker in maps.

**Comment by LauDijksterhuis** [comment]
Hi Guys,

I tried the new markers on smaller maps like: Netherlands, France, India and it seems to work quite accuratly. The Y axis is off like small amounts. Sadly since the WorldMap instructions dont have clear GEO point of wheren the map starts and end it is more hard to make it accurate. Therefor not possible to support for these maps (this is the same for the USA map)

However, digging in to the Y-axis problem more, I found this (see picture below) on Wikipedia and I think this is what causes the slight offset on the maps. When above the equator the location of the point seems more "upwards" of where it should be. When below the equator the location of the point seems more "downwards" of where it should be.

I think the scale factor is to blame and I will look in to how to account for that.

image

**Comment by EArminjon** [comment]
Yep, I think the logic that I used just did operation around a x / y chart without taking into account the round factor of the earth. If I put some point on a map like Siberia X it would be also wrong.

I need to compute this earth round factor to update X and Y.

**Pull request merged**
